apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 6
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: ghcr.io/superbrothers-sandbox/try-envoy-grpc/hello
        name: hello
        imagePullPolicy: IfNotPresent
        args: ["-client", "-addr", "envoy:8080", '-client.interval', '3s']
        env:
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: info
