apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  template:
    spec:
      containers:
      - image: docker.pkg.github.com/superbrothers-sandbox/try-envoy-grpc/hello
        name: hello
        args: ["-client", "-addr", "server:8888", "-client.interval", "3s"]
