apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  name: envoy
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 9901
    protocol: TCP
    targetPort: 9901
    name: admin
  selector:
    app: envoy
