apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envoy
  name: envoy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - image: docker.io/envoyproxy/envoy:v1.16.0
        name: envoy
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: x-envoy-livenessprobe
              value: healthz
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: x-envoy-livenessprobe
              value: healthz
          initialDelaySeconds: 3
      volumes:
      - name: config
        configMap:
          name: envoy-config
